/* Dados ilustrativos para a apresentação. Na versão dinâmica virão da API/CMS. */

const IMG = (window.FA_BASE || "") + "assets/img/";

const CATEGORIES = {
  brows: { pt: "Sobrancelhas", en: "Brows" },
  lashes: { pt: "Cílios", en: "Lashes" },
  hair: { pt: "Cabelo", en: "Hair" },
  body: { pt: "Corpo", en: "Body" },
  kits: { pt: "Kits", en: "Sets" },
};

const FREE_SHIPPING = 299;

const PRODUCTS = [
  {
    id: "defining-gel",
    cat: "brows",
    name: { pt: "Defining Gel", en: "Defining Gel" },
    sub: { pt: "Gel modelador para sobrancelhas", en: "Brow shaping gel" },
    size: "20g",
    price: 89.9,
    badge: { pt: "Mais vendido", en: "Best seller" },
    rating: 4.9,
    reviews: 312,
    order: 1,
    images: ["card-defining-gel.jpg", "defining-gel-espelho.jpg"],
    gallery: ["defining-gel-modelo.jpg", "defining-gel-espelho.jpg", "card-defining-gel.jpg"],
    desc: {
      pt: "Efeito lifting imediato para sobrancelhas alinhadas, volumosas e com acabamento natural o dia inteiro. Fórmula transparente, que não deixa resíduos nem pesa nos fios.",
      en: "Instant lifting effect for groomed, fuller brows with a natural finish that lasts all day. A clear formula that leaves no residue and never weighs hairs down.",
    },
    benefits: {
      pt: ["Efeito brow lifting por até 24h", "Acabamento transparente e natural", "Não craquela, não descasca e não pesa", "Enriquecido com pantenol e extrato de rosa"],
      en: ["Brow lifting effect for up to 24h", "Clear, natural finish", "No cracking, flaking or heaviness", "Enriched with panthenol and rose extract"],
    },
    howTo: {
      pt: "Com a escovinha, aplique uma pequena quantidade nos fios, penteando de baixo para cima. Modele no formato desejado e aguarde 30 segundos para fixar.",
      en: "Using the spoolie, apply a small amount to the hairs, brushing upwards. Shape as desired and allow 30 seconds to set.",
    },
    ingredients: "Aqua, Glycerin, PVP, Panthenol, Rosa Centifolia Flower Extract, Hydrolyzed Keratin, Phenoxyethanol.",
  },
  {
    id: "growth-elixir",
    cat: "lashes",
    name: { pt: "Growth Elixir", en: "Growth Elixir" },
    sub: { pt: "Sérum de crescimento · cílios e sobrancelhas", en: "Growth serum · lashes & brows" },
    size: "10ml",
    price: 129.9,
    badge: { pt: "Novo", en: "New" },
    badgeStyle: "dark",
    rating: 4.8,
    reviews: 198,
    order: 2,
    images: ["card-growth-elixir.jpg"],
    gallery: ["growth-elixir-modelo.jpg", "card-growth-elixir.jpg"],
    desc: {
      pt: "Nutrição profunda para cílios e sobrancelhas mais longos, densos e fortes. Resultados visíveis a partir de 4 semanas de uso contínuo.",
      en: "Deep nourishment for longer, denser and stronger lashes and brows. Visible results from 4 weeks of continuous use.",
    },
    benefits: {
      pt: ["Fortalece os fios desde a raiz", "Estimula o crescimento natural", "Reduz a queda e a quebra", "Peptídeos biomiméticos + biotina"],
      en: ["Strengthens hairs from the root", "Boosts natural growth", "Reduces shedding and breakage", "Biomimetic peptides + biotin"],
    },
    howTo: {
      pt: "À noite, com o rosto limpo, aplique uma fina camada na raiz dos cílios superiores e nas sobrancelhas. Use diariamente por, no mínimo, 8 semanas.",
      en: "At night, on a clean face, apply a thin layer along the upper lash line and on the brows. Use daily for at least 8 weeks.",
    },
    ingredients: "Aqua, Butylene Glycol, Myristoyl Pentapeptide-17, Biotin, Panthenol, Sodium Hyaluronate, Arginine.",
  },
  {
    id: "anti-estrias",
    cat: "body",
    name: { pt: "Anti Estrias", en: "Anti Stretch Marks" },
    sub: { pt: "Sérum ultra concentrado · Gênese Derma", en: "Ultra concentrated serum · Gênese Derma" },
    size: "200ml",
    price: 159.9,
    badge: { pt: "Lançamento", en: "Launch" },
    badgeStyle: "bronze",
    rating: 4.9,
    reviews: 87,
    order: 3,
    images: ["card-anti-estrias.jpg", "boutique.jpg"],
    gallery: ["card-anti-estrias.jpg", "boutique.jpg"],
    desc: {
      pt: "Sérum ultra concentrado com o Núcleo Bio-Ativo exclusivo Gênese Derma, que atua na prevenção e na redução visível de estrias, devolvendo firmeza e elasticidade à pele.",
      en: "Ultra concentrated serum powered by the exclusive Gênese Derma Bio-Active Core, helping prevent and visibly reduce stretch marks while restoring firmness and elasticity.",
    },
    benefits: {
      pt: ["Melhora a elasticidade da pele", "Uniformiza textura e tom", "Absorção rápida, toque seco", "Núcleo Bio-Ativo exclusivo"],
      en: ["Improves skin elasticity", "Evens out texture and tone", "Fast absorbing, dry touch", "Exclusive Bio-Active Core"],
    },
    howTo: {
      pt: "Aplique duas vezes ao dia sobre a pele limpa, com movimentos circulares, até a completa absorção. Ideal para abdômen, quadris, coxas e seios.",
      en: "Apply twice daily to clean skin using circular motions until fully absorbed. Ideal for abdomen, hips, thighs and breasts.",
    },
    ingredients: "Aqua, Centella Asiatica Extract, Rosa Moschata Seed Oil, Niacinamide, Sodium Hyaluronate, Bakuchiol, Tocopherol.",
  },
  {
    id: "kit-brow",
    cat: "kits",
    name: { pt: "Kit Brow Ritual", en: "Brow Ritual Set" },
    sub: { pt: "Defining Gel + Growth Elixir", en: "Defining Gel + Growth Elixir" },
    size: "20g + 10ml",
    price: 199.9,
    old: 219.8,
    badge: { pt: "Kit · -9%", en: "Set · -9%" },
    rating: 4.9,
    reviews: 64,
    order: 4,
    images: ["defining-gel-espelho.jpg", "card-growth-elixir.jpg"],
    gallery: ["defining-gel-espelho.jpg", "card-growth-elixir.jpg", "defining-gel-modelo.jpg"],
    desc: {
      pt: "O ritual completo para sobrancelhas: o Growth Elixir nutre e estimula o crescimento à noite, e o Defining Gel modela e fixa durante o dia.",
      en: "The complete brow ritual: Growth Elixir nourishes and boosts growth overnight, while Defining Gel shapes and sets throughout the day.",
    },
    benefits: {
      pt: ["Rotina dia e noite", "Sobrancelhas mais cheias e alinhadas", "Economia em relação aos itens avulsos", "Embalagem presenteável"],
      en: ["Day and night routine", "Fuller, groomed brows", "Savings vs. buying separately", "Gift-ready packaging"],
    },
    howTo: {
      pt: "Noite: aplique o Growth Elixir nos fios limpos. Manhã: modele as sobrancelhas com o Defining Gel.",
      en: "Night: apply Growth Elixir to clean hairs. Morning: shape brows with Defining Gel.",
    },
    ingredients: "Consulte a composição individual de cada produto.",
  },
  {
    id: "serum-capilar",
    cat: "hair",
    name: { pt: "Elixir Capilar Gold", en: "Gold Hair Elixir" },
    sub: { pt: "Sérum reparador de pontas", en: "Repairing hair serum" },
    size: "30ml",
    price: 119.9,
    rating: 4.7,
    reviews: 143,
    order: 5,
    images: ["card-serum-capilar.jpg", "categoria-cabelo.jpg"],
    gallery: ["card-serum-capilar.jpg", "categoria-cabelo.jpg"],
    desc: {
      pt: "Óleo-sérum leve com óleos nobres que sela as pontas, controla o frizz e entrega brilho espelhado sem pesar.",
      en: "A lightweight oil-serum with precious oils that seals split ends, tames frizz and delivers mirror-like shine without weighing hair down.",
    },
    benefits: {
      pt: ["Sela as pontas duplas", "Controle do frizz por 72h", "Brilho espelhado", "Proteção térmica até 230°C"],
      en: ["Seals split ends", "72h frizz control", "Mirror-like shine", "Heat protection up to 230°C"],
    },
    howTo: {
      pt: "Aplique de 2 a 3 gotas no comprimento e nas pontas, com os cabelos úmidos ou secos. Não enxágue.",
      en: "Apply 2 to 3 drops to lengths and ends on damp or dry hair. Do not rinse.",
    },
    ingredients: "Cyclopentasiloxane, Argania Spinosa Kernel Oil, Camellia Oleifera Seed Oil, Tocopherol, Parfum.",
  },
  {
    id: "mascara-gold",
    cat: "hair",
    name: { pt: "Máscara Nutritiva Gold", en: "Gold Nourishing Mask" },
    sub: { pt: "Nutrição intensa · todos os tipos de cabelo", en: "Intense nourishment · all hair types" },
    size: "250g",
    price: 99.9,
    old: 119.9,
    badge: { pt: "-17%", en: "-17%" },
    rating: 4.8,
    reviews: 121,
    order: 6,
    images: ["card-mascara-gold.jpg", "categoria-cabelo.jpg"],
    gallery: ["card-mascara-gold.jpg", "categoria-cabelo.jpg"],
    desc: {
      pt: "Máscara de tratamento com manteigas vegetais e queratina que devolve maciez, força e movimento aos fios em apenas 5 minutos.",
      en: "A treatment mask with plant butters and keratin that restores softness, strength and movement in just 5 minutes.",
    },
    benefits: {
      pt: ["Nutrição profunda em 5 minutos", "Maciez e movimento", "Reduz a quebra em até 80%", "Livre de sulfatos e parabenos"],
      en: ["Deep nourishment in 5 minutes", "Softness and movement", "Reduces breakage by up to 80%", "Sulfate and paraben free"],
    },
    howTo: {
      pt: "Após o shampoo, aplique mecha a mecha no comprimento e nas pontas. Deixe agir por 5 minutos e enxágue.",
      en: "After shampooing, apply section by section to lengths and ends. Leave on for 5 minutes and rinse.",
    },
    ingredients: "Aqua, Cetearyl Alcohol, Butyrospermum Parkii Butter, Hydrolyzed Keratin, Panthenol, Parfum.",
  },
  {
    id: "body-mist",
    cat: "body",
    name: { pt: "Body Mist Lumière", en: "Lumière Body Mist" },
    sub: { pt: "Bruma perfumada iluminadora", en: "Illuminating scented mist" },
    size: "120ml",
    price: 109.9,
    rating: 4.6,
    reviews: 76,
    order: 7,
    images: ["card-body-mist.jpg"],
    gallery: ["card-body-mist.jpg"],
    desc: {
      pt: "Bruma corporal com micropartículas de brilho dourado e notas de flor de laranjeira, baunilha e âmbar. Perfuma e ilumina a pele.",
      en: "A body mist with golden shimmer micro-particles and notes of orange blossom, vanilla and amber. Scents and illuminates the skin.",
    },
    benefits: {
      pt: ["Brilho dourado sutil", "Fragrância de longa duração", "Hidratação leve", "Fórmula vegana"],
      en: ["Subtle golden glow", "Long-lasting fragrance", "Light hydration", "Vegan formula"],
    },
    howTo: {
      pt: "Borrife a cerca de 20 cm do corpo, sobre a pele limpa e seca.",
      en: "Spray about 20 cm from the body onto clean, dry skin.",
    },
    ingredients: "Alcohol Denat., Aqua, Parfum, Glycerin, Mica, CI 77891, Aloe Barbadensis Leaf Juice.",
  },
  {
    id: "kit-ritual",
    cat: "kits",
    name: { pt: "Kit Ritual Completo", en: "Complete Ritual Set" },
    sub: { pt: "Sobrancelhas, cílios e cabelo", en: "Brows, lashes & hair" },
    size: "4 itens",
    price: 379.9,
    old: 439.6,
    badge: { pt: "Edição limitada", en: "Limited edition" },
    badgeStyle: "dark",
    rating: 5,
    reviews: 29,
    order: 8,
    images: ["categoria-cabelo.jpg", "card-defining-gel.jpg"],
    gallery: ["categoria-cabelo.jpg", "card-defining-gel.jpg", "card-growth-elixir.jpg", "card-serum-capilar.jpg"],
    desc: {
      pt: "Defining Gel, Growth Elixir, Elixir Capilar Gold e Máscara Nutritiva Gold em uma caixa de presente exclusiva. O ritual Female A completo.",
      en: "Defining Gel, Growth Elixir, Gold Hair Elixir and Gold Nourishing Mask in an exclusive gift box. The complete Female A ritual.",
    },
    benefits: {
      pt: ["4 best-sellers em um só kit", "Caixa de presente exclusiva", "Economia de R$ 59,70", "Frete grátis"],
      en: ["4 best sellers in one set", "Exclusive gift box", "Save R$ 59.70", "Free shipping"],
    },
    howTo: {
      pt: "Siga o modo de uso indicado em cada produto do kit.",
      en: "Follow the directions on each product in the set.",
    },
    ingredients: "Consulte a composição individual de cada produto.",
  },
  {
    id: "kit-corpo",
    cat: "kits",
    name: { pt: "Kit Corpo Iluminado", en: "Glow Body Set" },
    sub: { pt: "Anti Estrias + Body Mist Lumière", en: "Anti Stretch Marks + Lumière Body Mist" },
    size: "200ml + 120ml",
    price: 239.9,
    old: 269.8,
    badge: { pt: "Kit · -R$ 29", en: "Set · -R$ 29" },
    rating: 4.8,
    reviews: 41,
    order: 9,
    images: ["card-anti-estrias.jpg", "card-body-mist.jpg"],
    gallery: ["card-anti-estrias.jpg", "card-body-mist.jpg", "boutique.jpg"],
    desc: {
      pt: "O cuidado completo para o corpo: o sérum Anti Estrias trata e devolve elasticidade, e o Body Mist Lumière perfuma e ilumina a pele.",
      en: "Complete body care: the Anti Stretch Marks serum treats and restores elasticity, while Lumière Body Mist scents and illuminates the skin.",
    },
    benefits: {
      pt: ["Tratamento + finalização", "Pele firme, macia e iluminada", "Economia de R$ 29,90", "Embalagem presenteável"],
      en: ["Treatment + finishing", "Firm, soft and glowing skin", "Save R$ 29.90", "Gift-ready packaging"],
    },
    howTo: {
      pt: "Aplique o Anti Estrias após o banho e, com a pele seca, borrife o Body Mist.",
      en: "Apply Anti Stretch Marks after showering and, once skin is dry, spritz Body Mist.",
    },
    ingredients: "Consulte a composição individual de cada produto.",
  },
];

/* Tons de fundo usados pela Versão 2 nos cards */
const TINTS = {
  "defining-gel": "#F4DED6",
  "growth-elixir": "#F6E9D4",
  "anti-estrias": "#EDE3F0",
  "kit-brow": "#F4DED6",
  "serum-capilar": "#F5EBCB",
  "mascara-gold": "#F2E2CF",
  "body-mist": "#E6EDE3",
  "kit-ritual": "#EADBCB",
  "kit-corpo": "#F3E4DA",
};

const REVIEWS = [
  {
    name: "Mariana S.",
    city: "São Paulo, SP",
    rating: 5,
    date: "12/09/2026",
    title: { pt: "Virou indispensável", en: "Now a must-have" },
    text: {
      pt: "Fixa o dia todo e não deixa aquele aspecto duro. Minhas sobrancelhas ficam alinhadas e naturais. Já estou no segundo pote!",
      en: "Holds all day without that stiff look. My brows stay groomed and natural. I'm already on my second jar!",
    },
  },
  {
    name: "Camila R.",
    city: "Belo Horizonte, MG",
    rating: 5,
    date: "03/09/2026",
    title: { pt: "Embalagem linda, resultado melhor ainda", en: "Beautiful packaging, even better results" },
    text: {
      pt: "A experiência começa na caixa. O produto entrega exatamente o que promete, e a textura é muito agradável.",
      en: "The experience starts with the box. It delivers exactly what it promises and the texture is lovely.",
    },
  },
  {
    name: "Juliana A.",
    city: "Lisboa, PT",
    rating: 4,
    date: "28/08/2026",
    title: { pt: "Ótimo custo-benefício", en: "Great value" },
    text: {
      pt: "Rende muito e chegou super rápido aqui em Portugal. Só queria que tivesse uma versão maior!",
      en: "Lasts ages and arrived really fast here in Portugal. I just wish there was a bigger size!",
    },
  },
];
